#!/usr/bin/env bash

python train.py \
    --dataset agriseg \
    --val_dataset agriseg \
    --wild_dataset imagenet \
    --arch network.lraspp.LRASPP \
    --city_mode 'train' \
    --sgd \
    --lr_schedule poly \
    --lr 0.0025 \
    --poly_exp 0.9 \
    --max_cu_epoch 10000 \
    --class_uniform_pct 0.5 \
    --class_uniform_tile 1024 \
    --crop_size 768 \
    --scale_min 0.5 \
    --scale_max 2.0 \
    --rrotate 0 \
    --max_iter 60000 \
    --bs_mult 4 \
    --gblur \
    --color_aug 0.5 \
    --fs_layer 1 1 1 0 0 \
    --cont_proj_head 256 \
    --wild_cont_dict_size 393216 \
    --lambda_cel 0.1 \
    --lambda_sel 1.0 \
    --lambda_scr 10.0 \
    --date 2306 \
    --exp lraspp_agriseg_wildnet \
    --ckpt ./logs/ \
    --tb_path ./logs/